default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ukt-project-manager_development

test:
  <<: *default
  database: ukt-project-manager_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: ukt-project-manager_production
  username: ukt-project-manager
  password: <%= ENV['DATABASE_PASSWORD'] %>
